#Use Python Image
FROM python:latest
# Install apt dependencies
COPY . .

RUN pip3 install flask flask-sqlalchemy PyMySQL cryptography
EXPOSE 5000
ENTRYPOINT ["/usr/local/bin/python3", "app.py"] 
# Copy contents into image
 
# run pip dependencies
 
# Expose correct port

# Create an entrypoint

