apiVersion: apps/v1
kind: Deployment
metadata:
  name: app1
  labels:
    app: app1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app1
  template:
    metadata:
      labels:
        app: app1
    spec:
      containers:
      - name: app1
        env:
        - name: DATABASE_URI
          valueFrom:
            secretKeyRef:
              name: dburi
              key: dburi
        image: agrisjakob/app1
        ports:
        - name: http-port
          containerPort: 5000

---

apiVersion: v1
kind: Service
metadata:
  name: app1
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 5000
  selector:
    app: app1

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: app2
  labels:
    app: app2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app2
  template:
    metadata:
      labels:
        app: app2
    spec:
      containers:
      - name: app2
        image: agrisjakob/app2
        ports:
        - name: http-port2
          containerPort: 5001

---

apiVersion: v1
kind: Service
metadata:
  name: app2
spec:
  selector:
    app: app2
  ports:
    - protocol: TCP
      port: 5001
      targetPort: 5001

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: app3
  labels:
    app: app3
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app3
  template:
    metadata:
      labels:
        app: app3
    spec:
      containers:
      - name: app3
        image: agrisjakob/app3
        ports:
        - name: http-port3
          containerPort: 5002

---
apiVersion: v1
kind: Service
metadata:
  name: app3
spec:
  selector:
    app: app3
  ports:
    - protocol: TCP
      port: 5002
      targetPort: 5002

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: app4
  labels:
    app: app4
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app4
  template:
    metadata:
      labels:
        app: app4
    spec:
      containers:
      - name: app4
        image: agrisjakob/app4
        ports:
        - name: http-port4
          containerPort: 5003

---
apiVersion: v1
kind: Service
metadata:
  name: app4
spec:
  selector:
    app: app4
  ports:
    - protocol: TCP
      port: 5003
      targetPort: 5003

